runtime: python310

entrypoint: gunicorn -b :$PORT myproject.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "myproject.settings_gae"
  SECRET_KEY: "your-production-secret-key-here-make-it-long-and-random"
  ALLOWED_HOSTS: ".*"
  DEBUG: "False"
  DATABASE_URL: "sqlite:///db.sqlite3"

handlers:
- url: /static
  static_dir: static

- url: /media
  static_dir: media

- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
